import React, { useEffect, useRef, useState } from 'react';
import { GoogleGenAI } from '@google/genai';

const testLead = { leadId: 'demo-rajesh', name: 'Rajesh', companyName: 'ABC Engineering', city: 'Pune', state: 'Maharashtra', industry: 'Engineering', languagePreference: 'Hindi', udyamStatus: 'Unknown', zedStatus: 'Interested' };
const base64 = (buffer: ArrayBuffer) => { let binary = ''; for (const byte of new Uint8Array(buffer)) binary += String.fromCharCode(byte); return btoa(binary); };

export function MeeraPlayground() {
  const [status, setStatus] = useState('Disconnected'); const [events, setEvents] = useState<string[]>([]); const [customer, setCustomer] = useState(''); const [assistant, setAssistant] = useState(''); const [latency, setLatency] = useState<number | undefined>();
  const socket = useRef<WebSocket | null>(null); const directSession = useRef<any>(null); const stream = useRef<MediaStream | null>(null); const audio = useRef<AudioContext | null>(null); const processor = useRef<ScriptProcessorNode | null>(null); const nextAudio = useRef(0); const lastSpeechAt = useRef(0); const sentEndOfSpeech = useRef(false); const noiseFloor = useRef(.004); const speechFrames = useRef(0); const customerSpeaking = useRef(false);
  const log = (text: string) => setEvents(current => [`${new Date().toLocaleTimeString()}  ${text}`, ...current].slice(0, 14));
  const send = (message:any) => { if (directSession.current) { if (message.type === 'audio') directSession.current.sendRealtimeInput({ media: { data: message.data, mimeType: `audio/pcm;rate=${message.sampleRate}` } }); if (message.type === 'audio.end') directSession.current.sendRealtimeInput({ audioStreamEnd: true }); return; } if (socket.current?.readyState === WebSocket.OPEN) socket.current.send(JSON.stringify(message)); };
  const stopMic = () => { if (processor.current) send({ type: 'audio.end' }); processor.current?.disconnect(); stream.current?.getTracks().forEach(track => track.stop()); processor.current = null; };
  const play = async (data: string) => { const ctx = audio.current ||= new AudioContext({ sampleRate: 24000 }); const raw = Uint8Array.from(atob(data), char => char.charCodeAt(0)).buffer; const view = new DataView(raw); const buffer = ctx.createBuffer(1, raw.byteLength / 2, 24000); for (let i = 0; i < buffer.length; i++) buffer.getChannelData(0)[i] = view.getInt16(i * 2, true) / 32768; const source = ctx.createBufferSource(); source.buffer = buffer; source.connect(ctx.destination); nextAudio.current = Math.max(nextAudio.current, ctx.currentTime); source.start(nextAudio.current); nextAudio.current += buffer.duration; };
  const connect = async () => { if (socket.current?.readyState === WebSocket.OPEN || directSession.current) return; setStatus('Connecting…'); const local = ['127.0.0.1', 'localhost'].includes(location.hostname); const remoteGateway = import.meta.env.VITE_VOICE_GATEWAY_URL as string | undefined; if (!local && !remoteGateway) { try { const issued = await fetch('/api/live-token', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ lead: testLead }) }); const credentials = await issued.json(); if (!issued.ok || !credentials.token) throw new Error(credentials.error || 'Token request failed'); const ai = new GoogleGenAI({ apiKey: credentials.token, httpOptions: { apiVersion: 'v1alpha' } }); directSession.current = await ai.live.connect({ model: credentials.model, callbacks: { onopen: () => { setStatus(`Connected · ${credentials.model} · ${credentials.voice}`); log('Live session connected'); }, onmessage: async message => { const content = message.serverContent; if (content?.inputTranscription?.text) setCustomer(content.inputTranscription.text); if (content?.outputTranscription?.text) setAssistant(content.outputTranscription.text); for (const part of content?.modelTurn?.parts || []) if (part.inlineData?.data) await play(part.inlineData.data); if (content?.interrupted) { nextAudio.current = 0; log('assistant.interrupted'); } }, onerror: event => { setStatus(`Error: ${event.error?.message || 'Live connection failed'}`); }, onclose: () => { directSession.current = null; stopMic(); setStatus('Disconnected'); } } }); return; } catch (error) { setStatus(`Error: ${error instanceof Error ? error.message : 'Connection failed'}`); log('Public Live connection failed'); return; } } const endpoint = local ? 'ws://127.0.0.1:3002/live' : remoteGateway!; const ws = socket.current = new WebSocket(endpoint); ws.onopen = () => ws.send(JSON.stringify({ type: 'start', callId: crypto.randomUUID(), lead: testLead })); ws.onmessage = async ({ data }) => { const message = JSON.parse(data); if (message.type === 'ready') { setStatus(`Connected · ${message.model} · ${message.voice}`); log('Live session connected'); } if (message.type === 'audio') await play(message.data); if (message.type === 'transcript') (message.event.type === 'customer.transcript' ? setCustomer : setAssistant)(message.event.text); if (message.type === 'event') { log(message.event.type); if (message.latencyMs) setLatency(message.latencyMs); } if (message.type === 'error') { setStatus(`Error: ${message.message}`); log(message.message); } }; ws.onerror = () => { setStatus('Connection failed. Please retry.'); log('Live gateway connection failed'); }; ws.onclose = () => { stopMic(); setStatus('Disconnected'); } };
  const startMic = async () => { if (!socket.current || socket.current.readyState !== WebSocket.OPEN) return log('Connect first.'); const media = stream.current = await navigator.mediaDevices.getUserMedia({ audio: { channelCount: 1, echoCancellation: true, noiseSuppression: true, autoGainControl: true } }); const ctx = audio.current ||= new AudioContext(); await ctx.resume(); const source = ctx.createMediaStreamSource(media); const node = processor.current = ctx.createScriptProcessor(1024, 1, 1); lastSpeechAt.current = Date.now(); sentEndOfSpeech.current = false; customerSpeaking.current = false; speechFrames.current = 0; node.onaudioprocess = event => { const values = event.inputBuffer.getChannelData(0); let energy = 0; for (const value of values) energy += value * value; const rms = Math.sqrt(energy / values.length), threshold = Math.max(.018, noiseFloor.current * 3.5), voiceFrame = rms > threshold, now = Date.now(); if (!voiceFrame) noiseFloor.current = Math.min(.02, noiseFloor.current * .985 + rms * .015); speechFrames.current = voiceFrame ? Math.min(8, speechFrames.current + 1) : 0; if (speechFrames.current >= 3) { customerSpeaking.current = true; lastSpeechAt.current = now; if (sentEndOfSpeech.current) { sentEndOfSpeech.current = false; nextAudio.current = 0; socket.current?.send(JSON.stringify({ type: 'interrupt' })); } } else if (customerSpeaking.current && !sentEndOfSpeech.current && now - lastSpeechAt.current >= 500) { customerSpeaking.current = false; sentEndOfSpeech.current = true; socket.current?.send(JSON.stringify({ type: 'audio.end' })); log('Customer turn finalized'); } if (!sentEndOfSpeech.current) { const pcm = new Int16Array(values.length); for (let i = 0; i < values.length; i++) pcm[i] = Math.max(-1, Math.min(1, values[i])) * 32767; if (socket.current?.readyState === WebSocket.OPEN) socket.current.send(JSON.stringify({ type: 'audio', data: base64(pcm.buffer), sampleRate: ctx.sampleRate })); } }; source.connect(node); node.connect(ctx.destination); setStatus('Listening…'); log(`Microphone started at ${ctx.sampleRate} Hz · background-noise filter enabled`); };
  const interrupt = () => { nextAudio.current = 0; send({ type: 'interrupt' }); log('Playback cancelled for barge-in'); };
  const end = () => { stopMic(); directSession.current?.close(); directSession.current = null; socket.current?.send(JSON.stringify({ type: 'end' })); socket.current?.close(); };
  useEffect(() => () => { stopMic(); socket.current?.close(); }, []);
  return <main style={{ maxWidth: 1080, margin: '0 auto', padding: '32px', fontFamily: 'Inter, system-ui', color: '#132238' }}><p style={{ color: '#5c53d8', fontWeight: 700, letterSpacing: 1 }}>DEVELOPMENT PLAYGROUND</p><h1 style={{ margin: '0 0 8px' }}>Meera · Gemini Live</h1><p>Secure browser-to-backend realtime microphone test. The browser never receives your Gemini key.</p><div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', margin: '24px 0' }}><button onClick={connect}>Connect</button><button onClick={startMic}>Start microphone</button><button onClick={stopMic}>Stop</button><button onClick={interrupt}>Interrupt</button><button onClick={end}>End session</button></div><p><b>Status:</b> {status} {latency && <> · <b>Connection latency:</b> {latency} ms</>}</p><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}><section style={{ padding: 18, border: '1px solid #dbe1ea', borderRadius: 12 }}><b>Customer transcript</b><p>{customer || 'Waiting for speech…'}</p></section><section style={{ padding: 18, border: '1px solid #dbe1ea', borderRadius: 12 }}><b>Meera transcript</b><p>{assistant || 'Waiting for Meera…'}</p></section></div><section style={{ marginTop: 16, padding: 18, borderRadius: 12, background: '#101827', color: '#d8e5ff' }}><b>Session events</b><pre style={{ whiteSpace: 'pre-wrap', marginBottom: 0 }}>{events.join('\n') || 'No events yet.'}</pre></section></main>;
}
